### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by she40841** [jcweaver997/MapleStoryBot#2]
Built successfully after finding the correct repo for interceptor.dll

Now, when running, I get this output:

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Emgu.CV.Cuda.CudaInvoke.gpuMatUpload(IntPtr gpuMat, IntPtr arr)
   at Emgu.CV.Cuda.GpuMat.Upload(IInputArray arr)
   at maplestorybot.MS2.Start() in C:\Users\XXXX\Desktop\MS2\MapleStoryBot-master\maplestorybot\MS2.cs:line 76
   at maplestorybot.Program.Main(String[] args) in C:\Users\XXXX\Desktop\MS2\MapleStoryBot-master\maplestorybot\Program.cs:line 9
```

I have ensured that all the EMGU refs are correct and up to date. Any suggestions?

**Comment by jcweaver997** [comment]
Thank you for your interest in the project!
I'm actually surprised you got that far with no instructions.
I am currently uploading a README, along with all the dlls needed. Follow those instructions and let me know if you still have this issue. All the vision processing libraries are pretty big files, and my project at the moment is 4.25 GB.
If you want any support for any features, let me know.

**Comment by jcweaver997** [comment]
@she40841 sorry about the wait, but everything is committed. I had to remove a lot of the nuget packages because the file sizes were too large. The nuget package list should still be present though, and can be 'restored' with the nuget package manager

**Comment by she40841** [comment]
Dude, thank you so much for replying! I'll be home from work in an hour or so and will try it all out then report back.

**Comment by she40841** [comment]
So that compiled perfectly, which is amazing! The bot runs correctly, however sending keystrokes doesn't appear to be functioning. Interception has installed correctly, as far as I can tell, and image processing is working perfectly (the bot counts attempts correctly) but it will not send space to begin fishing or to move the lure within the blue zone.

**Comment by jcweaver997** [comment]
Sorry about the late reply, been pretty chaotic with the chaos raids coming out. I'm not exactly sure what's going on in your case. Maybe try reinstalling http://www.oblita.com/interception.html ?

**Comment by jcweaver997** [comment]
Someone else had this issue, and they had windows 8. The c# interception driver at https://github.com/jasonpang/Interceptor states that it does not work for windows 8. Do you have windows 8 as well?
